#!/usr/bin/env bash

# Languages
defaults write -globalDomain AppleLanguages -array "en-US" "ko-US"
defaults write -globalDomain NSLinguisticDataAssetsRequested -array "en" "en_US" "fr" "ko" "ko_US" "nl"



# Mouse and Trackpad
defaults write "com.apple.mouse.scaling" -int 3
defaults write "com.apple.trackpad.scaling" -int 3
defaults write "com.apple.swipescrolldirection" -int 0

defaults write "com.apple.AppleMultitouchMouse" "MouseButtonMode" "TwoButton"
defaults write "com.apple.AppleMultitouchTrackpad" "Clicking" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "DragLock" -int 0
defaults write "com.apple.AppleMultitouchTrackpad" "Dragging" -int 0
defaults write "com.apple.AppleMultitouchTrackpad" "FirstClickThreshold" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "ForceSuppressed" -int 0
defaults write "com.apple.AppleMultitouchTrackpad" "SecondClickThreshold" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadFiveFingerPinchGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadFourFingerHorizSwipeGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadFourFingerPinchGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadFourFingerVertSwipeGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadHandResting" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadHorizScroll" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadMomentumScroll" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadPinch" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadCornerSecondaryClick" -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadRotate" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadScroll" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerDrag" -int 0
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerHorizSwipeGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerTapGesture" -int 0
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadThreeFingerVertSwipeGesture" -int 2
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadTwoFingerDoubleTapGesture" -int 1
defaults write "com.apple.AppleMultitouchTrackpad" "TrackpadTwoFingerFromRightEdgeSwipeGesture" -int 3

# Input Sources and Language

defaults write "com.apple.HIToolbox" "AppleDictationAutoEnable" -int 0
defaults write "com.apple.HIToolbox" "AppleEnabledInputSources" \
-array \
'<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>0</integer><key>KeyboardLayout Name</key><string>U.S.</string></dict>' \
'<dict><key>InputSourceKind</key><string>Non Keyboard Input Method</string><key>Bundle ID</key><string>com.apple.PressAndHold</string></dict>' \
'<dict><key>InputSourceKind</key><string>Input Mode</string><key>Bundle ID</key><string>com.apple.inputmethod.Korean</string><key>Input Mode</key><string>com.apple.inputmethod.Korean.2SetKorean</string></dict>' \
'<dict><key>InputSourceKind</key><string>Keyboard Input Method</string><key>Bundle ID</key><string>com.apple.inputmethod.Korean</string></dict>' \
'<dict><key>InputSourceKind</key><string>Non Keyboard Input Method</string><key>Bundle ID</key><string>com.apple.inputmethod.EmojiFunctionRowItem</string></dict>'

defaults write "com.apple.HIToolbox" "AppleInputSourceHistory" \
-array \
'<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>0</integer><key>KeyboardLayout Name</key><string>U.S.</string></dict>' \
'<dict><key>InputSourceKind</key><string>Input Mode</string><key>Bundle ID</key><string>com.apple.inputmethod.Korean</string><key>Input Mode</key><string>com.apple.inputmethod.Korean.2SetKorean</string></dict>'

defaults write "com.apple.HIToolbox" "AppleSelectedInputSources" \
-array \
'<dict><key>InputSourceKind</key><string>Non Keyboard Input Method</string><key>Bundle ID</key><string>com.apple.PressAndHold</string></dict>' \
'<dict><key>InputSourceKind</key><string>Non Keyboard Input Method</string><key>Bundle ID</key><string>com.apple.inputmethod.EmojiFunctionRowItem</string></dict>' \
'<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>0</integer><key>KeyboardLayout Name</key><string>U.S.</string></dict>'

# Screen Saver, Desktop and Dock
defaults write -globalDomain NSTableViewDefaultSizeMode -int 2

# System Preferences > Dock > Size:
defaults write "com.apple.dock" "tilesize" -int 36
defaults write "com.apple.dock" "largesize" -int 54

# System Preferences > Dock > Magnification:
defaults write "com.apple.dock" "magnification" -int 1

# Finder > Preferences > Show all filename extensions
defaults write -globalDomain "AppleShowAllExtensions" -bool false

# Show Battery Percentage
defaults write com.apple.menuextra.battery "ShowPercent" -bool true

# Kill affected apps
apps=( Dock Finder SystemUIServer )

for app in "${apps[@]}"; do
  killall "${app}" > /dev/null 2>&1
done

echo "Done. Note that some of these changes require a logout/restart to take effect."